import Head from "next/head";
import Header from "./components/header";
import Nav from "./components/nav";
import Secstion from "./components/secstion";
import "bootstrap/dist/css/bootstrap.css";
import AboutUs from "./components/about";
import Features from "./components/features";
import Gallerey from "./components/gallerey";

export default function Home() {
  return (
    <>
      <Head>
        <title>Мох и Перья</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Secstion />
        <AboutUs />
        <Features />
        <Gallerey />
      </main>
    </>
  );
}
